### ISSUE TITLE
[Feature] Filter forks

### ISSUE THREAD

**Issue by t0mmili** [vladkens/ghstats#15]
Here's interesting idea. Possibility to filter all forked repos. I find it useful. Maybe some will as well.

My idea is to introduce new flag `GHS_FILTER_FORKS=(true|1 / false|0)`.

I have this feature already prepared 😄 Will post a PR soon.

**Comment by vladkens** [comment]
Hi @t0mmili. I merged your [PR](https://github.com/vladkens/ghstats/pull/16) and updated it as we discussed in the comments:

- added forks filter in `GHS_FILTER` with `!fork`
- also added `!archived`
- parse `GHS_FILTER` once, instead of parsing it every time it needed

Doc: https://github.com/vladkens/ghstats?tab=readme-ov-file#filter-repos

**Comment by vladkens** [comment]
Released in [v0.6.0](https://github.com/vladkens/ghstats/releases/tag/v0.6.0)

**Comment by t0mmili** [comment]
Thanks @vladkens! That's unexpected what you did with `private` though. I thought it will be handled by `GHS_FILTER`... Now it's inconsistent imo.
Anyway, closing this one.

**Comment by vladkens** [comment]
There are two reasons why I did private differently:
1) backward compatibility – if I make private by default – users who have publicly posted their ghstats may have data leaks
2) there can be many private repos (I assume that mostly of them is organizations), so by default the number of requests to API may increase a lot and rate limit may happen (adding a new filter heuristic like "+private" seems ugly for me, because default filter is include all)
