### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by modem7** [vladkens/ghstats#6]
To make things appear neater, is it possible to add a page title for tabs?

Currently, it's just showing as ghstats.mydomain.com in the tab.

My thiking is:

```
Homepage: GHStats (or similar)
Repo: Repoowner/reponame
```

Low priority I know.

**Comment by 101br03k** [comment]
Taking a quick look it seams that because there is no title set in src/main.rs it pickes the default wich in my case is the LAN IPv4 adres and port inluding the repowner and repo name with slashes. 

Static should be easy to do, dynamic a little harder but not to hard since the var that sets the repo name in the page sould be able to put in there. Will try it localy but can't push it to gh because I already have a brance for #3 in order to order pr and issues / feature requests using github templates. 

Also would like to point out there is no icon set. Will just set one in there, will just be the owner  icon for now. 
Also no rust for long time, this can take some time. 

edit: typo's

**Comment by vladkens** [comment]
@modem7 nice catch. I will include this into next release.

**Comment by vladkens** [comment]
Released in [v0.3.0](https://github.com/vladkens/ghstats/releases/tag/v0.3.0)
